// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxSqq1YkicvjPXSwP0zRIwRD9tbawP9JM',
    appId: '1:358035935546:web:81ac9720f8c68e8bcc4003',
    messagingSenderId: '358035935546',
    projectId: 'avaliacao-oa',
    authDomain: 'avaliacao-oa.firebaseapp.com',
    storageBucket: 'avaliacao-oa.firebasestorage.app',
    measurementId: 'G-3R8B35X5R2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwzfog1m2Uy5t6yBdoktoOL8l0Dwa3RLU',
    appId: '1:358035935546:android:4e3d0d1609824c91cc4003',
    messagingSenderId: '358035935546',
    projectId: 'avaliacao-oa',
    storageBucket: 'avaliacao-oa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWq0NLod6cGzIitCkTJlqpEgpKF330ZV8',
    appId: '1:358035935546:ios:34b0ced036dd5e37cc4003',
    messagingSenderId: '358035935546',
    projectId: 'avaliacao-oa',
    storageBucket: 'avaliacao-oa.firebasestorage.app',
    iosBundleId: 'com.example.ortoCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWq0NLod6cGzIitCkTJlqpEgpKF330ZV8',
    appId: '1:358035935546:ios:34b0ced036dd5e37cc4003',
    messagingSenderId: '358035935546',
    projectId: 'avaliacao-oa',
    storageBucket: 'avaliacao-oa.firebasestorage.app',
    iosBundleId: 'com.example.ortoCare',
  );
}
